title: Saaransh Pandey
logo: ./pics/Picture1.png
description: [Resume](https://drive.google.com/file/d/1Ib1v2n-JW8n6_GM-7FmQFwnzJcfYdxlm/view?usp=sharing) [LinkedIn](https://www.linkedin.com/in/saaransh-pandey)
show_downloads: false
theme: jekyll-theme-minimal
